In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
crop_data = pd.read_csv("crop_recommendation.csv")

In [3]:
crop_data

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [4]:
crop_data.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [5]:
crop_data.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
crop_data['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [7]:
# train test split

x = crop_data.iloc[:, :-1]
y = crop_data.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 76)

In [8]:
X_train

        N    P    K  temperature   humidity        ph    rainfall
163    86   36   24    26.549864  72.891873  5.787268   73.336361
703    42   73   25    34.036792  67.211138  6.501869   73.235736
1203   36  125  196    37.465668  80.659687  6.155261   66.838723
83     67   43   39    26.043720  84.969072  5.999969  186.753677
470     3   60   19    25.746794  40.719259  4.820788  100.779163
...   ...  ...  ...          ...        ...       ...         ...
1064   92   85   51    29.221186  81.081836  5.740765  108.861647
1359   81    6   55    24.889105  85.870591  6.110143   51.706991
1409  108   26   52    28.826290  94.267653  6.201798   26.238385
2090   80   43   43    23.787560  74.367941  6.014572  172.644265
1415   95   27   55    28.472126  91.213221  6.160414   20.886204

[1540 rows x 7 columns]

In [9]:
y_train

163          maize
703      blackgram
1203        grapes
83            rice
470     pigeonpeas
           ...
1064        banana
1359    watermelon
1409     muskmelon
2090          jute
1415     muskmelon
Name: label, Length: 1540, dtype: object

In [10]:
model = RandomForestClassifier()

In [11]:
model.fit(X_train,  y_train)

RandomForestClassifier()

In [12]:
prediction = model.predict(X_test)

In [13]:
accuracy = model.score(X_test, y_test)

In [14]:
print("Accuracy : ", accuracy)

Accuracy :  0.990909090909091

In [15]:
new_features = [[104, 18,30,23.60301571,60.39647474,6.779832611000002,140.9370415]]
predicted_crop = model.predict(new_features)

c:\Jupyter Notebook\ml_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [16]:
print("Predicted Value : ", predicted_crop)

Predicted Value :  ['coffee']

In [17]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))